#!/usr/bin/env python3
"""Regenerate the gptme plugin registry static page.

Queries GitHub for repos with gptme-plugin, gptme-skill, and gptme-mcp-server topics,
then generates a sortable static HTML page.

Usage:
    export GITHUB_TOKEN=ghp_...
    python3 scripts/regenerate.py
"""

import json
import subprocess
import sys
from datetime import datetime, timezone

TOPICS = {
    "gptme-plugin": "Plugin",
    "gptme-skill": "Skill",
    "gptme-mcp-server": "MCP Server",
}

OUTPUT = "index.html"


def gh_search(topic: str) -> list[dict]:
    """Search GitHub repos by topic using gh CLI."""
    result = subprocess.run(
        [
            "gh", "search", "repos",
            "--topic", topic,
            "--json", "fullName,description,stargazersCount,updatedAt,language",
            "--limit", "100",
            "--sort", "updated",
        ],
        capture_output=True, text=True,
        timeout=30,
    )
    if result.returncode != 0:
        print(f"gh search failed for {topic}: {result.stderr}", file=sys.stderr)
        return []
    repos = json.loads(result.stdout)
    # Deduplicate by fullName
    seen = set()
    unique = []
    for r in repos:
        key = r["fullName"]
        if key not in seen:
            seen.add(key)
            r["_topic"] = topic
            unique.append(r)
    return unique


def generate_page(entries: list[dict]) -> str:
    """Generate the static HTML page."""
    rows_html = ""
    for e in sorted(entries, key=lambda x: x.get("stargazersCount", 0), reverse=True):
        name = e.get("fullName", "unknown")
        desc = (e.get("description") or "").strip()
        desc = desc[:120] + "..." if len(desc) > 120 else desc
        stars = e.get("stargazersCount", 0)
        updated = e.get("updatedAt", "")[:10] if e.get("updatedAt") else ""
        lang = e.get("language") or ""
        topic_labels = [t for t in TOPICS if t in e.get("_topics", [])]
        type_badge = " | ".join(
            f'<span class="tag tag-{t.split("-")[-1]}">{TOPICS[t]}</span>'
            for t in topic_labels
        )
        rows_html += f"""\
        <tr>
          <td><a href="https://github.com/{name}">{name}</a></td>
          <td>{type_badge}</td>
          <td class="num">{stars}</td>
          <td>{updated}</td>
          <td>{lang}</td>
          <td>{desc}</td>
        </tr>
"""
    nav_tabs = " ".join(
        f'<button class="tab" data-topic="{t}">{label}</button>'
        for t, label in TOPICS.items()
    )

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>gptme Plugin Registry</title>
  <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'><text y='14' font-size='14'>🔌</text></svg>">
  <link rel="stylesheet" href="assets/style.css">
</head>
<body>
  <div class="container">
    <header>
      <h1>🔌 gptme Plugin Registry</h1>
      <p class="subtitle">Discover plugins, skills, and MCP servers for
        <a href="https://gptme.org">gptme</a> —
        a personal AI agent for the terminal.</p>
    </header>

    <div class="filters">
      {nav_tabs}
      <button class="tab tab-all active" data-topic="all">All</button>
    </div>

    <section class="stats">
      <span>Total: <strong>{len(entries)}</strong> entries</span>
      <span>Updated: <strong>{now}</strong></span>
    </section>

    <div class="table-wrap">
      <table id="registry-table">
        <thead>
          <tr>
            <th data-sort="name">Repository</th>
            <th>Type</th>
            <th data-sort="stars" class="num">★ Stars</th>
            <th data-sort="updated">Updated</th>
            <th>Language</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
{rows_html}
        </tbody>
      </table>
    </div>

    <footer>
      <p>To list your plugin, add the <code>gptme-plugin</code>, <code>gptme-skill</code>, or
        <code>gptme-mcp-server</code> topic to your GitHub repo.
      <br>Generated by <code>scripts/regenerate.py</code> &mdash;
        <a href="https://github.com/gptme/registry.gptme.org">source</a></p>
    </footer>
  </div>

  <script src="assets/script.js"></script>
</body>
</html>"""


def main():
    all_entries = []
    by_name = {}
    for topic in TOPICS:
        repos = gh_search(topic)
        for r in repos:
            key = r["fullName"]
            if key not in by_name:
                r["_topics"] = [topic]
                by_name[key] = r
                all_entries.append(r)
            else:
                # Repo carries multiple registry topics; record them all.
                by_name[key]["_topics"].append(topic)
    seen = by_name.keys()

    html = generate_page(all_entries)
    with open(OUTPUT, "w") as f:
        f.write(html)
    print(f"Regenerated {OUTPUT}: {len(all_entries)} entries, {len(seen)} unique repos")


if __name__ == "__main__":
    main()
